package com.planet_ink.grinder;
import java.awt.*;
import java.util.*;



public class GrinderAreaSelect extends Dialog {

    Frame myParent=null;
	public GrinderAreaSelect(Frame parent, boolean modal)
	{
		super(parent, modal);
        myParent=parent;
		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
        
		//{{INIT_CONTROLS
		setLayout(null);
		setBackground(new java.awt.Color(255,255,128));
		setForeground(java.awt.Color.blue);
		setFont(new Font("Dialog", Font.BOLD, 12));
		setSize(249,150);
		setVisible(false);
		label1.setText("Select an Area:");
		add(label1);
		label1.setBounds(24,0,96,36);
		okButton.setLabel("Load");
		add(okButton);
		okButton.setBounds(168,36,66,24);
		CancelButton.setLabel("Cancel");
		add(CancelButton);
		CancelButton.setBounds(168,108,66,24);
		add(list1);
		list1.setBounds(12,36,144,96);
		setTitle("MUDGrinder - Open an Area");
		setResizable(false);
		//}}
        
		//{{REGISTER_LISTENERS
		SymWindow aSymWindow = new SymWindow();
		this.addWindowListener(aSymWindow);
		SymAction lSymAction = new SymAction();
		okButton.addActionListener(lSymAction);
		CancelButton.addActionListener(lSymAction);
		SymKey aSymKey = new SymKey();
		okButton.addKeyListener(aSymKey);
		CancelButton.addKeyListener(aSymKey);
		//}}

	}
    
	public GrinderAreaSelect(Frame parent, String title, boolean modal)
	{
		this(parent, modal);
		setTitle(title);
	}

	public void addNotify()
	{
		// Record the size of the window prior to calling parents addNotify.
                Dimension d = getSize();

		super.addNotify();

		// Only do this once.
		if (fComponentsAdjusted)
			return;

		// Adjust components according to the insets
		Insets insets = getInsets();
		setSize(insets.left + insets.right + d.width, insets.top + insets.bottom + d.height);
		Component components[] = getComponents();
		for (int i = 0; i < components.length; i++)
		{
			Point p = components[i].getLocation();
			p.translate(insets.left, insets.top);
			components[i].setLocation(p);
		}

		// Used for addNotify check.
		fComponentsAdjusted = true;
	}

	public void setVisible(boolean b)
	{
	    if (b)
	    {
    		Rectangle bounds = getParent().getBounds();
    		Rectangle abounds = getBounds();

    		setLocation(bounds.x + (bounds.width - abounds.width)/ 2,
    			 bounds.y + (bounds.height - abounds.height)/2);
	    }

		super.setVisible(b);
	}

	//{{DECLARE_CONTROLS
	java.awt.Label label1 = new java.awt.Label();
	java.awt.Button okButton = new java.awt.Button();
	java.awt.Button CancelButton = new java.awt.Button();
	java.awt.List list1 = new java.awt.List(4);
	//}}
    
    // Used for addNotify check.
	boolean fComponentsAdjusted = false;

	class SymAction implements java.awt.event.ActionListener
	{
		public void actionPerformed(java.awt.event.ActionEvent event)
		{
			Object object = event.getSource();
			if (object == okButton)
				okButton_ActionPerformed(event);
			else if (object == CancelButton)
				CancelButton_ActionPerformed(event);
		}
	}

	void okButton_ActionPerformed(java.awt.event.ActionEvent event)
	{
	    if(list1.getSelectedIndex()<0)
	        return;
	    String newName=list1.getSelectedItem();
	    ((MUDGrinder)myParent).suddenlyAnArea(newName);
		try {
			this.dispose();
		} catch (Exception e) {
		}
		// to do: code goes here.
	}


	class SymWindow extends java.awt.event.WindowAdapter
	{
		public void windowOpened(java.awt.event.WindowEvent event)
		{
			Object object = event.getSource();
			if (object == GrinderAreaSelect.this)
				GrinderAreaSelect_WindowOpened(event);
		}

		public void windowClosing(java.awt.event.WindowEvent event)
		{
			Object object = event.getSource();
			if (object == GrinderAreaSelect.this)
				GrinderAreaSelect_WindowClosing(event);
		}
	}

	void GrinderAreaSelect_WindowClosing(java.awt.event.WindowEvent event)
	{
		// to do: code goes here.
	}


	void GrinderAreaSelect_WindowOpened(java.awt.event.WindowEvent event)
	{
	    Vector areas=TheGrinder.getAreasList();
        if(areas.size()==0)
        {
            label1.setText("No areas found!");
            label1.setForeground(Color.red);
            okButton.setEnabled(false);
        }
	    // error condition goes here
	    
	    for(int a=0;a<areas.size();a++)
	    {
	        String areaName=(String)areas.elementAt(a);
	        list1.add(areaName);
	    }
	}

	void CancelButton_ActionPerformed(java.awt.event.ActionEvent event)
	{
		try {
			this.dispose();
		} catch (Exception e) {
		}

			 
	}

	class SymKey extends java.awt.event.KeyAdapter
	{
		public void keyPressed(java.awt.event.KeyEvent event)
		{
			Object object = event.getSource();
			if ((object == okButton)&&((event.getKeyCode()==13)||(event.getKeyCode()==10)))
                okButton_ActionPerformed(null);
			if ((object == CancelButton)&&((event.getKeyCode()==13)||(event.getKeyCode()==10)))
                CancelButton_ActionPerformed(null);	
		}
	}
}
