#This file assumes that Sun's SDK has been installed (to any directory...)
#Before using this on a UNIX machine, you must 'chmod 755 makemud.bat' to make this file executable by the UNIX machine
#DO NOT PUT A FORWARD SLASH AT THE END!!!
Java_Home=/home/knoppix/j2sdk1.4.2

#Leave this line alone...
classpath=$Java_Home/lib/dt.jar;$Java_Home/lib/tools.jar

$Java_Home/bin/javadoc -classpath $classpath -d ./docs -J-Xmx128m com/planet_ink/coffee_mud/Abilities/*.java com/planet_ink/coffee_mud/Abilities/Archon/*.java com/planet_ink/coffee_mud/Abilities/Bard/*.java com/planet_ink/coffee_mud/Abilities/Common/*.java com/planet_ink/coffee_mud/Abilities/Druid/*.java com/planet_ink/coffee_mud/Abilities/Fighter/*.java com/planet_ink/coffee_mud/Abilities/Languages/*.java com/planet_ink/coffee_mud/Abilities/Misc/*.java com/planet_ink/coffee_mud/Abilities/Paladin/*.java com/planet_ink/coffee_mud/Abilities/Prayers/*.java com/planet_ink/coffee_mud/Abilities/Properties/*.java com/planet_ink/coffee_mud/Abilities/Diseases/*.java com/planet_ink/coffee_mud/Abilities/Poisons/*.java com/planet_ink/coffee_mud/Abilities/Ranger/*.java com/planet_ink/coffee_mud/Abilities/Skills/*.java com/planet_ink/coffee_mud/Abilities/Songs/*.java com/planet_ink/coffee_mud/Abilities/Specializations/*.java com/planet_ink/coffee_mud/Abilities/Spells/*.java com/planet_ink/coffee_mud/Abilities/Thief/*.java com/planet_ink/coffee_mud/Abilities/Traps/*.java com/planet_ink/coffee_mud/application/*.java com/planet_ink/coffee_mud/Areas/*.java com/planet_ink/coffee_mud/Behaviors/*.java com/planet_ink/coffee_mud/CharClasses/*.java com/planet_ink/coffee_mud/Clans/*.java com/planet_ink/coffee_mud/Commands/*.java com/planet_ink/coffee_mud/Commands/base/*.java com/planet_ink/coffee_mud/Commands/sysop/*.java com/planet_ink/coffee_mud/Commands/extra/*.java com/planet_ink/coffee_mud/common/*.java com/planet_ink/coffee_mud/exceptions/*.java com/planet_ink/coffee_mud/Exits/*.java com/planet_ink/coffee_mud/interfaces/*.java com/planet_ink/coffee_mud/Items/*.java com/planet_ink/coffee_mud/Items/Weapons/*.java com/planet_ink/coffee_mud/Items/MiscMagic/*.java com/planet_ink/coffee_mud/Items/Armor/*.java com/planet_ink/coffee_mud/Locales/*.java com/planet_ink/coffee_mud/MOBS/*.java com/planet_ink/coffee_mud/Races/*.java com/planet_ink/coffee_mud/system/*.java com/planet_ink/coffee_mud/utils/*.java com/planet_ink/coffee_mud/web/*.java com/planet_ink/coffee_mud/web/macros/*.java com/planet_ink/coffee_mud/web/macros/grinder/*.java com/planet_ink/fakedb/*.java
