c:\jdk1.3\bin\javac com\planet_ink\coffee_mud\Abilities\*.java
c:\jdk1.3\bin\javac com\planet_ink\coffee_mud\Abilities\Archon\*.java
c:\jdk1.3\bin\javac com\planet_ink\coffee_mud\Abilities\Common\*.java
c:\jdk1.3\bin\javac com\planet_ink\coffee_mud\Abilities\Druid\*.java
c:\jdk1.3\bin\javac com\planet_ink\coffee_mud\Abilities\Fighter\*.java
c:\jdk1.3\bin\javac com\planet_ink\coffee_mud\Abilities\Languages\*.java
c:\jdk1.3\bin\javac com\planet_ink\coffee_mud\Abilities\Misc\*.java
c:\jdk1.3\bin\javac com\planet_ink\coffee_mud\Abilities\Paladin\*.java
c:\jdk1.3\bin\javac com\planet_ink\coffee_mud\Abilities\Prayers\*.java
c:\jdk1.3\bin\javac com\planet_ink\coffee_mud\Abilities\Properties\*.java
c:\jdk1.3\bin\javac com\planet_ink\coffee_mud\Abilities\Ranger\*.java
c:\jdk1.3\bin\javac com\planet_ink\coffee_mud\Abilities\Skills\*.java
c:\jdk1.3\bin\javac com\planet_ink\coffee_mud\Abilities\Songs\*.java
c:\jdk1.3\bin\javac com\planet_ink\coffee_mud\Abilities\Specializations\*.java
c:\jdk1.3\bin\javac com\planet_ink\coffee_mud\Abilities\Spells\*.java
c:\jdk1.3\bin\javac com\planet_ink\coffee_mud\Abilities\Thief\*.java
c:\jdk1.3\bin\javac com\planet_ink\coffee_mud\Abilities\Traps\*.java
c:\jdk1.3\bin\javac com\planet_ink\coffee_mud\application\*.java
c:\jdk1.3\bin\javac com\planet_ink\coffee_mud\Areas\*.java
c:\jdk1.3\bin\javac com\planet_ink\coffee_mud\Behaviors\*.java
c:\jdk1.3\bin\javac com\planet_ink\coffee_mud\CharClasses\*.java
c:\jdk1.3\bin\javac com\planet_ink\coffee_mud\commands\*.java
c:\jdk1.3\bin\javac com\planet_ink\coffee_mud\commands\base\*.java
c:\jdk1.3\bin\javac com\planet_ink\coffee_mud\commands\base\sysop\*.java
c:\jdk1.3\bin\javac com\planet_ink\coffee_mud\common\*.java
c:\jdk1.3\bin\javac com\planet_ink\coffee_mud\Exits\*.java
c:\jdk1.3\bin\javac com\planet_ink\coffee_mud\interfaces\*.java
c:\jdk1.3\bin\javac com\planet_ink\coffee_mud\Items\*.java
c:\jdk1.3\bin\javac com\planet_ink\coffee_mud\Items\Weapons\*.java
c:\jdk1.3\bin\javac com\planet_ink\coffee_mud\Items\MiscMagic\*.java
c:\jdk1.3\bin\javac com\planet_ink\coffee_mud\Items\Armor\*.java
c:\jdk1.3\bin\javac com\planet_ink\coffee_mud\Locales\*.java
c:\jdk1.3\bin\javac com\planet_ink\coffee_mud\MOBS\*.java
c:\jdk1.3\bin\javac com\planet_ink\coffee_mud\Races\*.java
c:\jdk1.3\bin\javac com\planet_ink\coffee_mud\system\*.java
c:\jdk1.3\bin\javac com\planet_ink\coffee_mud\utils\*.java
c:\jdk1.3\bin\javac com\planet_ink\coffee_mud\web\*.java
c:\jdk1.3\bin\javac com\planet_ink\coffee_mud\web\macros\*.java
