#You should really input a name for your MUD below....
#FYI - the nohup command will make a nohup.out file, usually in the CofferMud (directory where you start this from) directory - it will log the server messages...
nohup java -classpath "." -Xms65535000 -Xmx115535000 com.planet_ink.coffee_mud.application.MUD "Your mud's Name Here" &
