# this script is for the outlaw who stole the lolly pop
RAND_PROG 10
if has($i 'a lolly pop')
	emote sucks on $k lolly pop.
endif
~

SPEECH_PROG lolly pop steal take little lolly? pop? steal? take? boy? girl? little?
if has($i 'a lolly pop')
	say "$n" You'll never get this lolly pop!
	emote slurps on the lolly pop.
else
	say "$n" Yes, but .. hmm.. where'd it go?
	emote looks around for the lolly pop.
endif
~