# this script is for the human chosen to be the note bearer

SPEECH_PROG 'I have a delivery from'
	if has($n 'a post-marked package')
		say "$n" Thank you very much, go ahead and give it to me
	endif
~
	

GIVE_PROG p a post-marked package
	whisper "$n" Thank you.  Here's the stipend you were promised.
	if !QUESTWINNER($n *)
		mpexp $n 10%
		mpoload QuestPoint
		give "a quest point" "$n"
	endif
	mpsetvar $n * didit
	mpoload 100
	give 100 "$n"
	mpquestwin $n *
	mpendquest *
~