# this script is for the human chosen to be the note bearer

SPEECH_PROG 'I have a delivery from'
	if has($n 'a most secret note')
		say "$n" It is not for me.  Give it to someone else.
	endif
~
	

GIVE_PROG p a most secret note
	whisper "$n" Thank you.  You've done well.
	if !QUESTWINNER($n delivery)
		mpexp $n 100
		mpoload QuestPoint
		give "a quest point" "$n"
	endif
	mpoload 100
	give 100 "$n"
	mpquestwin $n delivery
	mpendquest delivery
~