# this script is for the human chosen to be the note bearer

SPEED_PROG 'I have a delivery from'
	say $n Yes, that's for me.
~

GIVE_PROG p <DELIVERYITEM>
	say "$n" Thank you.  You've done well.
	if !QUESTWINNER($n <QUESTNAME>)
		mpexp $n 50%
		mpoload QuestPoint
		give "a quest point" "$n"
	endif
	mpsetvar $n <QUESTNAME> didit
	mpoload 100
	give 100 "$n"
	mpquestwin $n <QUESTNAME>
	mpendquest <QUESTNAME>
~