name: Development Snapshot Build

on:
  workflow_dispatch:  # Manual trigger
    inputs:
      dry_run:
        description: 'Set to true for a dry run'
        required: false
        default: 'true'

jobs:
  build_snapshot:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/develop')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Get Committer Date and Short Hash
        id: get_commit_info
        run: |
          COMMITTER_DATE=$(git log -1 --format=%ci | cut -d' ' -f1)
          SHORT_HASH=$(echo $GITHUB_SHA | cut -c1-7)  # Get the short commit hash
          echo "dev_revision=DEV_${COMMITTER_DATE}_${SHORT_HASH}" >> $GITHUB_ENV  # Format as DEV_YYYY-MM-DD_hash

      - name: Build Project (Dry Run)
        if: ${{ github.event.inputs.dry_run == 'true' }}
        run: |
          echo "Dry Run Mode: This would build the project with revision ${{ env.dev_revision }}"
          echo "Command: mvn clean package -Drevision=${{ env.dev_revision }}"

      - name: Build Project (Actual)
        if: ${{ github.event.inputs.dry_run != 'true' }}
        run: mvn clean package -Drevision=${{ env.dev_revision }}

      - name: Upload Artifact
        if: ${{ github.event.inputs.dry_run != 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: coffeemud-build-artifact
          path: target/*.jar